name: 'DiscoMcDisco Presents!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32636
title: 'All Things Disco...Speaks, Eats, Sleeps, Plays'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff9ee'
    - '#63240f'
    - '#dcb35f'
    - '#957a33'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.26234373287297785
purpose: []
